# Generated by Django 5.2 on 2025-05-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('queue_name', models.CharField(max_length=255)),
                ('actor_name', models.CharField(max_length=255)),
                ('message_json', models.JSONField()),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('enqueued', 'Enqueued'), ('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=255)),
            ],
        ),
    ]
