# Generated by Django 5.2.1 on 2025-05-22 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('organization_name', models.CharField(max_length=255)),
                ('person_id', models.UUIDField()),
                ('person_name', models.CharField(max_length=255)),
                ('file_name_1', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name_2', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success')], default='processing', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('queue_name', models.CharField(max_length=255)),
                ('actor_name', models.CharField(max_length=255)),
                ('message_json', models.JSONField()),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('queue_time', models.IntegerField(blank=True, null=True)),
                ('processing_time', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('enqueued', 'Enqueued'), ('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=255)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dramatiq_task_history_middleware.pipeline')),
            ],
        ),
    ]
