# Generated by Django 5.2 on 2025-05-16 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramatiq_task_history_middleware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('organization_id', models.CharField(max_length=255)),
                ('organization_name', models.CharField(max_length=255)),
                ('person_id', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255)),
                ('file_name_1', models.CharField(max_length=255)),
                ('file_name_2', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='pipeline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramatiq_task_history_middleware.pipeline'),
        ),
    ]
