# Generated by Django 5.2 on 2025-05-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramatiq_task_history_middleware', '0002_pipeline_task_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='file_name_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='file_name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='organization_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='person_id',
            field=models.UUIDField(),
        ),
    ]
