# Generated by Django 5.2 on 2025-05-16 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramatiq_task_history_middleware', '0003_alter_pipeline_file_name_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dramatiq_task_history_middleware.pipeline'),
        ),
    ]
