# Generated by Django 5.2.1 on 2025-05-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramatiq_task_history_middleware', '0004_alter_task_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success')], default='processing', max_length=255),
        ),
    ]
