# Generated by Django 5.2.1 on 2025-05-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramatiq_task_history_middleware', '0005_pipeline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='processing_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='queue_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
